### ISSUE TITLE
Language clarification index.md

### ISSUE THREAD

**Issue by disa-mhembere** [flashxio/FlashX-doc#1]
"FlashMatrix is a matrix computation engine that provides a small set of generalized matrix operations ..."

It was initially unclear to me that a small set is desirable & that it was just not a maturity issue.

**Comment by zheng-da** [comment]
i have updated the description on FlashMatrix. What do you think?

**Comment by disa-mhembere** [comment]
Nice! Much clearer but you'll for sure have a merge conflict with me now :(

**Comment by zheng-da** [comment]
did you push your update? let's try to merge them

**Comment by disa-mhembere** [comment]
There is an open pull request. Maybe I'll just pull the master branch and
fix issues and push. I don't think you favor pull requests lol

**Comment by zheng-da** [comment]
i just noticed your pull request and have merged it.
i like pull requests. it's just i don't get notification. maybe because it's not in my own account any more.
