### ISSUE TITLE
test quick start guide of FlashX

### ISSUE THREAD

**Issue by zheng-da** [flashxio/FlashX-doc#3]

**Comment by disa-mhembere** [comment]
# Comments

- I would remove the `$` in front of instructions so people can copy-paste
- Make NOTE --> **NOTE:** so it sticks out.
- Add a link to what the config options are that are available and what they
mean.
- There must be an extra space causing the link to not render
(see an [example config file] (https://github.com/flashxio/FlashX/blob/dev-zd/matrix/conf/run_test.txt)).
- Broken link in here: *Please check here for more advanced configuration of a*
- I think having a side-by-side view of the old `R` code with adapted `FlashR`
code would be better to show how *easy* it is to adapt existing code. The
example is also a bit verbose. Perhaps 2/3 shorter/simpler ones are  better ??
- There are quite a few grammar issues that could make it shorter & easier to
read.

**Comment by disa-mhembere** [comment]
While installing a newer version of R it asks:

```
Configuration file '/etc/bash_completion.d/R'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** R (Y/I/N/O/D/Z) [default=N] ?
```
Will people know what to answer so they don't *break* other things?

I said `Y`, but had to `sudo touch /usr/share/bash-completion/completions/R` to make it work since `apt` tries to `stat` that file and fails if it doesn't exist.

**Comment by disa-mhembere** [comment]
Is there a way to `> install_github("flashxio/FlashR")` with more than 1 thread?

I successfully installed FlashR on a clean AWS 14.04 instance and ran the example though.

**Comment by zheng-da** [comment]
do you know how to show two pieces of code side by side?
I want to do it as well. but i don't know how to do it with markdown.

**Comment by zheng-da** [comment]
I don't know how to which answer we should choose. I also chose Y and got the same problem.
It seems to me it's the problem of R in ubuntu. 
i don't know what the right solution is.

**Comment by zheng-da** [comment]
i don't think there is a way of compiling C code with more than one thread in R.

**Comment by disa-mhembere** [comment]
Oh think there is a git gist thing of some sort but I can't remember now.
I'll look after I workout :)

On Nov 21, 2016 6:58 PM, "Da Zheng" notifications@github.com wrote:

do you know how to show two pieces of code side by side?
I want to do it as well. but i don't know how to do it with markdown.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
https://github.com/flashxio/FlashX-doc/issues/3#issuecomment-262106117,
or mute the thread

**Comment by zheng-da** [comment]
I update the quick start guide in the example of using FlashR to run k-means.
I provide the link below to show how much we need to modify to run an existing R function in FlashR.
https://github.com/flashxio/FlashR-learn/commit/7143368ecfd8426cdb2197ffa1b2226fd435a024?diff=split

Ideally, we should show it in the same page, but I guess it kind of gives the idea.
